# Use uma imagem oficial do PostgreSQL como base
FROM postgres:16

# Defina variáveis de ambiente (opcional)
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=kanban

# Porta exposta
EXPOSE 5432
